server:
  port: 8081

spring:
  application:
    name: integration-template

management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health,prometheus
  endpoint:
    health.enabled: true
    prometheus.enabled: true

environment:
  stack: local
  region: ru-spb
  instance: node1
  application: ${spring.application.name}