global:
  scrape_interval:     15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'integration-template'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['integration-template:8081']
